---
title: "EOL_LF"
author: "samir"
date: "2023-09-04"
output: html_document
---

```{r libraries, echo=FALSE, warning=FALSE, message=FALSE}

library("readr")
library("viridis")
library("scales")
library("lubridate")
library("gsignal")
library("FactoMineR")
library("factoextra")
library("gplots")
library("heatwaveR")
library("dplyr")
library("imputeTS")
library("Metrics")
library("tidyr")
library("tseries")
library("forecast")
library("tsDyn")
library("tsoutliers")
library("seacarb")
library("lmodel2")
library("lmtest")
library("ggExtra")
library("corrplot")
library("ggcorrplot")
library("marelac")
library("spectral")
library("signal")
library("cowplot")
library("kableExtra")
library("EnvStats")

```

# Point B : surface (2007-2022) 
  
Utilisation of : na_seadec() function  
= Removes the seasonal component from the time series, performs imputation on the deseasonalized series and afterwards adds the seasonal component again.  
  
  
## Temperature & salinity

```{r interpolation temp & salinity, echo=FALSE, warning=FALSE, message=FALSE, fig.width=7,fig.height=5}

SOMLIT_pcO2 <- read_delim("../../Data/Data_PointB/DATA_SOMLIT_07-22_impute_0m.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE) %>% 
  dplyr::filter(datetime <= "2021-11-09")

impute_temp <- na_seadec(SOMLIT_pcO2$temperature, algorithm = "interpolation", find_frequency = F)
impute_sal <- na_seadec(SOMLIT_pcO2$salinity, algorithm = "interpolation", find_frequency = F)


SOMLIT_pcO2$temperature[is.na(SOMLIT_pcO2$pCO2_atmos)] <- "NA"

SOMLIT_pcO2 %>% 
  dplyr::filter(temperature == "NA") %>% 
  dplyr::group_by(Year) %>% 
  dplyr::summarise(number_of_NA = n()) %>% 
  ggplot(aes(x = Year, y = number_of_NA))  +
  geom_segment(aes(x = Year, xend = Year, y = 0, yend = number_of_NA), 
               color = "grey", linewidth = 2) +
  geom_point(size = 5, fill = "#689D71", shape = 21, color = "black") +
  coord_flip() +
  scale_y_continuous(name = "Nombre de données manquantes", limits = c(0,15), breaks = seq(0, 15, 1)) + 
  scale_x_discrete(name="", limits=c("2007":"2021"))

SOMLIT_pcO2 <- SOMLIT_pcO2 %>% 
  mutate(pCO2_atmos = as.numeric(pCO2_atmos))


#ggplot_na_gapsize(SOMLIT_pcO2$pCO2_atmos)


# ggplot_na_imputations(SOMLIT_pcO2$pCO2_atmos, SOMLIT_pcO2$impute_pCO2_atmos, x_axis_labels = SOMLIT_pcO2$datetime, xlab = "", 
#                       ylab=expression(paste(italic(p), CO[2], " atmosphérique ", "(atm)")), 
#                       title="", color_lines = "lightslategray",
#                       color_points = "steelblue", size_points = 1.2, size_imputations = 1.7) +
#   scale_x_date(date_breaks = "2 years", date_labels = "%Y") 
#   



```















```{r importation data SOMLIT clean, echo=FALSE, message=FALSE, warning=FALSE}
#period : jan. 2007 - dec. 2022
SOMLIT <- read_delim("./Data/data_PointB/DATA_SOMLIT_07-22_CLEAN.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

#selection data surface 1m 
SOMLIT <- SOMLIT %>% 
  dplyr::filter(depth == 0) %>% 
  rename(datetime=sampling_date, temp_SOM = temperature, sal_SOM = salinity) %>% 
  dplyr::select(datetime, temp_SOM, sal_SOM)
SOMLIT$datetime <- ymd(SOMLIT$datetime)

```

## Temperature

```{r moving average & mann kendall PtB - 2014, echo=FALSE, warning=FALSE, message=FALSE}

# data_somlit_ts <- read_delim("./Data/data_PointB/DATA_SOMLIT_07-22_impute_0m.csv",
#     delim = ";", escape_double = FALSE, trim_ws = TRUE) %>%
#   dplyr::filter(datetime >= "2014-01-07") %>%
#   mutate(Month = format(datetime, format="%m"))

#Transfome data into TS, frequency : 365.25/7 = 52.17857
ts_temp_som <- ts(SOMLIT$temp_SOM, start = c(2018,1), end = c(2022,52), freq = 52)

# look at the NA in the ts before filling
ggplot_na_distribution(ts_temp_som )

# filling datat(imputation) with na_seadec() = Removes the seasonal component from the time series, performs imputation on the deseasonalized series and afterwards adds the seasonal component again.
ts_seadec <-  na_seadec(ts_temp_som, algorithm = "ma",find_frequency = TRUE)  
# plot 
ggplot_na_imputations(x_with_na = ts_temp_som,
                          x_with_imputations = ts_seadec,
                          color_imputations = "gold")
 
 
#decompose on filled data : ts_seadec
ts_temp_som_decomp <- decompose(ts_seadec, type = "additive")

autoplot(ts_temp_som_decomp) +
  xlab(' ')

#remove seasonality :
ts_temp_som_less_season <- ts_temp_som_decomp$x - ts_temp_som_decomp$seasonal

plot_ts_temp_som_less_season <- autoplot(ts_temp_som_less_season) +
  xlab("") + ylab("Temp. (°C)") +
  ggtitle("Temperature time series at Pt B (without seasonality)") +
  geom_smooth(method=lm)

#regression values :
reg_val_ts_temp_som_less_season <- as.data.frame(plot_ts_temp_som_less_season$data)

model_ts_temp_less_season <- lm(formula=y~x, data=reg_val_ts_temp_som_less_season)
summary(model_ts_temp_less_season)


#plot with slope value :
plot_ts_temp_som_less_season <- autoplot(ts_temp_som_less_season) +
  xlab("") + ylab("Temp. (°C)") +
  ggtitle("Temperature time series at Pt B (without seasonality)") +
  geom_smooth(method=lm) +
  annotate(geom="text", x=4, y=24, label="slope :  0.01 ± 0.075 (non-significative)", color="black")

plot_ts_temp_som_less_season

FFtemp_som <- kendallSeasonalTrendTest(temp_SOM ~ month(datetime) + year(datetime), data = SOMLIT)
FFtemp_som$estimate

```