---
title: "TDT"
author: "Mégane"
date: "2023-05-22"
output: html_document
---

```{r libraries, echo=FALSE, warning=FALSE, message=FALSE}
library("readr")
library("viridis")
library("scales")
library("lubridate")
library("gsignal")
library("FactoMineR")
library("factoextra")
library("gplots")
library("heatwaveR")
library("dplyr")
library("imputeTS")
library("Metrics")
library("tidyr")
library("tseries")
library("forecast")
library("tsDyn")
library("tsoutliers")
library("seacarb")
library("lmodel2")
library("lmtest")
library("ggExtra")
library("corrplot")
library("ggcorrplot")
library("marelac")
library("kableExtra")
library("stringr")
library("berryFunctions")
library("LakeMetabolizer")
library("rMR")

```


## Calculation of trend detection time (TDT) : Sutton et al. (2022)  
  
  
#### Temperature :  
  
###### Point B : 2007-2022  
  

```{r importation data somlit - surface, echo=FALSE, warning=FALSE, message=FALSE}

data_PtB_surf_0722 <- read_delim("../Data/data_PointB/DATA_SOMLIT_07-22_impute_0m.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

data_PtB_surf_9522 <- read_delim("../Data/data_PointB/PointB_T_S_1995-2022_CLEAN_impute_0m.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)



## creation ts object :
#frequency : 365.25/7 = 52.17857
ts_temp_0722 <- ts(data_PtB_surf_0722$impute_temp, start = c(2007,1), end = c(2022,52), freq = 52)


## decompose function :
#type = additive because the seasonal pattern doesn't seem to increase in variation, seasonal pattern looks constant
ts_temp_0722_decomp <- decompose(ts_temp_0722, type = "additive")

autoplot(ts_temp_0722_decomp) +
  xlab(' ')

```
  
  

```{r remove seasonality, echo=FALSE, warning=FALSE, message=FALSE}

ts_temp_0722_less_season <- ts_temp_0722_decomp$x - ts_temp_0722_decomp$seasonal


plot_ts_temp_0722_less_season <- autoplot(ts_temp_0722_less_season) + 
  xlab("") + ylab("Temp. (°C)") +
  ggtitle("Sea surface temperature time series (without seasonality)") +
  geom_smooth(method=lm)


reg_val_less_season_0722 <- as.data.frame(plot_ts_temp_0722_less_season$data)

model_less_season_0722 <- lm(formula=y~x, data=reg_val_less_season_0722)
summary(model_less_season_0722) # slope : 0.058


#plot with slope value :
plot_ts_temp_0722_less_season <- autoplot(ts_temp_0722_less_season) + 
  xlab("") + ylab("Temp. (°C)") +
  ggtitle("Sea surface temperature time series (without seasonality)") +
  geom_smooth(method=lm) +
  annotate(geom="text", x=2015, y=23, label="slope : 0.058 ± 0.009 *", color="black")

plot_ts_temp_0722_less_season
##

```


```{r calcul TDT parameters, echo=FALSE, warning=FALSE, message=FALSE}

## σN calculation : 
TDT_sd <- sd(ts_temp_0722_decomp$random[27:806]) #1.134

## Φ calculation (lag 1) :
acf(ts_temp_0722_decomp$random[27:806], lag.max = 60, type = "cor", plot = F) # 0.674
TDT_acf <- 0.674

## ω0 :
TDT_slope <- 0.058

```



```{r TDT calculation, echo=FALSE, warning=FALSE, message=FALSE}

#test on temperature at Point B (2007-2022)

#formulae :

#Fac1 = (3.3 * σN)/|ω0|
#Fac2 = √[(1+Φ)/(1-Φ)]
#TDT = (Fac1 * Fac2)^(2/3)

#with :

# σN :  sd(noise) → decompose function
# ω0 : trend slope
# Φ : autocorr(noise) at lag 1


Fac1 <- (3.3 * TDT_sd)/abs(TDT_slope)
Fac2 <- sqrt((1 + TDT_acf)/(1 - TDT_acf))

TDT <- (Fac1 * Fac2)^(2/3) # 27.8 years



#uncertainty of TDT :

#192 months on 2007-2022 period

B <- (4/(3*sqrt(192))) * Fac2

uTDT_neg <- TDT * exp(-B)
uTDT <- TDT * exp(B)

#interval of years : (22.32 years to 34.52 years)
```
  
  

```{r TDT simplifié}

# ToE = (2*N)/S
# with 
# S : linear trend (per year)
# N : sd of the variable on the entire period, detrended

ts_temp_0722_less_trend <- ts_temp_0722_decomp$x - ts_temp_0722_decomp$trend


N <- sd(ts_temp_0722_less_trend, na.rm=TRUE) # 4.28
S <- 0.058 

ToE <- (2*N)/S # 147.5

```







###### EOL : 2014-2022  
  

```{r}

EOL_daily <- read_delim("../Data/EOL_13-23_1perday_morning.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE) %>% 
  rename(temperature=temp_eol_c, salinity=sal_eol_psu) %>% 
  mutate(datetime = as.POSIXct(datetime)) %>% 
  dplyr::filter(datetime >= "2014-01-07 01:00:00" & datetime <= "2022-12-31 01:00:00")

LM <- lm(EOL_daily$temperature ~ EOL_daily$datetime)

RES <- residuals(LM)

sd(RES)

acf(EOL_daily$temperature, type = "correlation", plot=T)


#TDT :
Fac1 <- (3.3 * 4.486381)/abs(0.050323128)

Fac2 <- sqrt((1 + 0.994)/(1 - 0.994))

TDT <- (Fac1 * Fac2)^(2/3) # 306.39 years


#uncertainty of TDT :

#192 months on 2007-2022 period

B <- (4/(3*sqrt(192))) * Fac2

uTDT_neg <- TDT * exp(-B)
uTDT <- TDT * exp(B)

#interval of years : (18.39 years to 28.44 years) or 23 ± 5 years





```







